Repository fastcam-sideproject/AllYouRaffle, pull requests merged in 2024-09, with the labels that each got.

#58 [feat] 메인 랜딩 페이지 목업
  api/raffle/raffleApi.ts
  app/globals.css
  components/Home/HomeHero.tsx
  components/Home/HomeInfo.tsx
  components/Home/HomeMain.tsx
  components/Items/ItemManual.tsx
  components/Items/ItemPopular.tsx
  components/Items/ItemStyle.tsx
Labels: style

#71 refactor: 타입 분리 및 타입 추가, 불필요한 import문 삭제, export default 네임으로 변경, 커스텀 훅으로 분리 등
  api/baseURL.ts
  api/raffle/adminApi.ts
  api/raffle/purchaseTicketApi.ts
  api/raffle/raffleApi.ts
  api/user/addressApi.ts
  api/user/myInfo.ts
  api/user/phoneNumberApi.ts
  api/user/ticketsApi.ts
  app/loading.tsx
  app/myInfo/memberInfo/page.tsx
  app/myInfo/page.tsx
  components/AddressForm.tsx
  components/AdminDashboard/AdminDashboard.tsx
  components/Banner/Banner.tsx
  components/Button/GoogleLoginButton.tsx
  components/Email/EmailForm.tsx
  components/Email/EmailPopUp.tsx
  components/ErrorPages/ErrorPage.tsx
  components/Header/HeaderNav.tsx
  components/Home/HomeHero.tsx
  components/Home/HomeInfo.tsx
  components/Home/HomeMain.tsx
  components/Items/Item.tsx
  components/Items/ItemComplete.tsx
  components/Items/ItemDetail.tsx
  components/Items/ItemGrid.tsx
  components/Items/ItemLoginModal.tsx
  components/Items/ItemManual.tsx
  components/Items/ItemStyle.tsx
  components/Modal/AddressModal.tsx
  components/Modal/PhoneNumberModal.tsx
  components/MyInfoStyle.tsx
  lib/hooks/useAddress.ts
  lib/hooks/useMyInfo.ts
  lib/hooks/useOrdererInfo.ts
  lib/hooks/usePhoneNumber.ts
  lib/hooks/useRaffleData.ts
  lib/types/address.ts
  lib/types/email.ts
  lib/types/item.ts
Labels: refactor

#72 refactor: 전화번호, 우편주소 수정 시 실시간으로 업데이트 되도록 수정
  components/payment/PhoneNumber.tsx
  lib/hooks/useAddress.ts
  lib/hooks/usePhoneNumber.ts
Labels: refactor

#73 fix: 타입 오류 수정 및 반환 타입 추가
  components/Button/GoogleLoginButton.tsx
  components/Email/EmailForm.tsx
  components/Footer/Footer.tsx
  components/Header/HeaderNav.tsx
  components/Items/Item.tsx
  components/Items/ItemDetail.tsx
  components/Items/ItemGrid.tsx
  components/Items/ItemStyle.tsx
  lib/hooks/useAddress.ts
  lib/hooks/useMyInfo.ts
  lib/hooks/usePhoneNumber.ts
  lib/hooks/useRaffleData.ts
  lib/types/item.ts
Labels: refactor

#79 feat: raffleItem 구매 기능 구현
  api/raffle/purchaseItemApi.ts
  api/raffle/raffleApi.ts
  app/purchase/[id]/page.tsx
  components/Items/ItemDetail.tsx
  components/Modal/RaffleItemConfirmationModal.tsx
  lib/types/item.ts
Labels: feat

#80 feat: 미니게임을 통해 응모권 획득 하도록 기능 구현
  components/Home/HomeHero.tsx
  components/MemoryCardGame.tsx
  components/NumberBaseballGame.tsx
  components/NumberGuessingGame.tsx
  lib/hooks/useTicketPlusOne.ts
  public/icon/cancel.svg
Labels: feat

#81 fix: myInfo, tickets API 함수에서 401 에러가 발생한다면 로그아웃 되도록하여 문제 해결
  api/user/myInfoApi.ts
  api/user/ticketsApi.ts
  components/AuthHandler.tsx
  lib/hooks/useMyInfo.ts
Labels: fix

#83 fix: 로그인한 유저의 주소가 없을 때 마이페이지로 들어가면 발생하는 에러 수정
  api/user/addressApi.ts
  api/user/phoneNumberApi.ts
  app/myInfo/memberInfo/page.tsx
  components/AddressForm.tsx
  components/payment/PhoneNumber.tsx
  lib/hooks/useAddress.ts
  lib/hooks/usePhoneNumber.ts
Labels: bug, fix

#84 feat: allyouraffle앱 링크로 이동되도록 추가
  components/Home/AppInstallBanner.tsx
  components/Home/HomeHero.tsx
  components/Home/HomeMain.tsx
  public/image/logo/googleplay.png
Labels: feat
